<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>DesktopWidgets.Toolkit</AssemblyName>
    <RootNamespace>DesktopWidgets.Toolkit</RootNamespace>
  </PropertyGroup>
</Project>
